name: Build and deploy ASP.Net Core Ui project to Azure Web App - BookCar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Ui project
        run: dotnet build CarRentFinalProject/Ui/Ui.csproj --configuration Release

      - name: Publish Ui project
        run: dotnet publish CarRentFinalProject/Ui/Ui.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-ui-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-ui-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'YOUR_AZURE_WEBAPP_NAME'  # buraya Azure Web App adını yaz
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D6531D35190A455FA70FF1C4FC5B3DF8 }}
