name: Build and deploy ASP.Net Core Ui project to Azure Web App - BookCar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Ui project
        run: dotnet build Ui/Ui.csproj --configuration Release

      - name: Publish Ui project
        run: dotnet publish Ui/Ui.csproj --configuration Release --output ./publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ui-artifact
          path: ./publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ui-artifact
          path: ./publish_output

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BookCar'  # Change to your actual Azure Web App name
          slot-name: 'Production'
          package: ./publish_output
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D6531D35190A455FA70FF1C4FC5B3DF8 }}
